# Change these first
owner: RishCoder-Tech
repo: CoguideUptime

sites:
  - name: Coguide
    url: https://coguide.ai
  - name: Coguide Backend
    url: https://login.coguide.ai
  
status-website:
  baseUrl: /CoguideUptime
  logoUrl: https://i.ibb.co/QFh1KXW/Screenshot-2024-10-09-at-6-47-22-PM-removebg-preview.png
  name: Coguide
  introTitle: "Welcome To The **Coguide** Status Page"
  introMessage: Hopefully This Site Always Stays Alive
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
